# docker-compose.yml

services:
  postgres:
    image: postgres:15
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kitab
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: localhost
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
