# docker-compose.yml

services:
  postgres:
    image: postgres:13
    ports:
      - "55432:55432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
