services:
  postgres:
    image: postgres:15
    ports:
      - 5455:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kitab
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_HOST: localhost
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - 6380:6379
    volumes:
      - redis:/data

  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - redis
    env_file:
      - .env.docker
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

volumes:
  postgres:
  redis:
