services:
  postgres:
    build:
      x-bake:
        cache-to: type=gha
      context: ./database
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookshelf
    volumes:
      - "postgres:/var/lib/postgresql/data"
volumes:
  postgres:
