# docker-compose.yml

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshelf
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
